FLASK_ADMIN_SWATCH = "paper"

SECRET_KEY = "123456790"

DATABASE_FILENAME = "example_app_01.db"
SQLALCHEMY_DATABASE_URI = "sqlite:///" + DATABASE_FILENAME
SQLALCHEMY_ECHO = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
